# Generated by Django 5.2.1 on 2025-06-21 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('cl_id', models.AutoField(primary_key=True, serialize=False)),
                ('dates', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('em_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('phone_num', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.IntegerField(null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('phone_num', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('tran_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tran_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('avail_participations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym.employee')),
            ],
            options={
                'verbose_name': 'Coach',
                'verbose_name_plural': 'Coaches',
            },
            bases=('gym.employee',),
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym.employee')),
            ],
            options={
                'verbose_name': 'Secretary',
                'verbose_name_plural': 'Secretaries',
            },
            bases=('gym.employee',),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('cl', models.ForeignKey(db_column='cl_id', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='gym.class')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='gym.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='tran',
            field=models.ForeignKey(blank=True, db_column='tran_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='gym.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sub',
            field=models.ForeignKey(db_column='sub_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='gym.subscription'),
        ),
        migrations.AddField(
            model_name='member',
            name='sub',
            field=models.ForeignKey(blank=True, db_column='sub_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='gym.subscription'),
        ),
        migrations.AddField(
            model_name='class',
            name='em',
            field=models.ForeignKey(db_column='em_id', on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gym.coach'),
        ),
    ]
