# Generated by Django 5.2.1 on 2025-06-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_employee_class_payment_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='age',
        ),
    ]
